title: Bicycle
author: robenkleene
email: contact@robenkleene.com
description: >
  Demo site for the Bicycle Jekyll theme.

twitter_username: robenkleene
github_username:  robenkleene
rss: rss

# show_excerpts: true
show_contents: true

markdown: kramdown
theme: bicycle
exclude:
  - Gemfile
  - Gemfile.lock
