title: Cyclist Jekyll
author: robenkleene
email: contact@robenkleene.com
description: >
  Demo site for the Cyclist Jekyll theme.

twitter_username: robenkleene
github_username:  robenkleene
rss: rss

# show_excerpts: true
show_contents: true
posts_limit: 15

markdown: kramdown
theme: cyclist-jekyll
exclude:
  - Gemfile
  - Gemfile.lock
