title: Cyclist Jekyll
author: robenkleene
email: contact@robenkleene.com
description: >
  Demo site for the Cyclist Jekyll theme.

rss: rss
cyclist_jekyll:
  social_links:
    twitter: robenkleene
    github:  robenkleene

# show_excerpts: true
show_contents: true
posts_limit: 15

markdown: kramdown
theme: cyclist-jekyll
exclude:
  - Gemfile
  - Gemfile.lock
