title: Cyclist
author: robenkleene
email: contact@robenkleene.com
description: >
  Demo site for the Cyclist Jekyll theme.

twitter_username: robenkleene
github_username:  robenkleene
rss: rss

# show_excerpts: true
show_contents: true

markdown: kramdown
theme: cyclist
exclude:
  - Gemfile
  - Gemfile.lock
